### PR TITLE
End to End tests and Questionnaire integration

### PR DESCRIPTION
**Pull request by fnobilia**
- All hardcode `Strings` have been converted in constants [RadarAvroConstants](https://github.com/RADAR-CNS/RADAR-MongoDB-Sink-Connector/blob/struct/src/main/java/org/radarcns/sink/util/RadarAvroConstants.java) and [MongoConstants](https://github.com/RADAR-CNS/RADAR-MongoDB-Sink-Connector/blob/struct/src/main/java/org/radarcns/sink/util/MongoConstants.java) in this way, other projects queuing MongoDb can reuse them.
- All converters now take advantages of [MongoDb Codec](http://api.mongodb.com/java/3.0/?org/bson/codecs/Codec.html)
- ~Created [converter](https://github.com/RADAR-CNS/RADAR-MongoDB-Sink-Connector/blob/struct/src/main/java/org/radarcns/sink/util/struct/AvroToStruct.java) from Avro to Struct schema~
- Created [Struct analyser](https://github.com/RADAR-CNS/RADAR-MongoDB-Sink-Connector/blob/struct/src/main/java/org/radarcns/sink/util/struct/StructAnalyser.java)
- Better documentation
- Added end to end and unit test for all converters

In the future the ~[Converter](https://github.com/RADAR-CNS/RADAR-MongoDB-Sink-Connector/blob/struct/src/main/java/org/radarcns/sink/util/struct/AvroToStruct.java)~ (substituted with the [Confluent](https://github.com/confluentinc/schema-registry/blob/master/avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java) one) and [Struct analyser](https://github.com/RADAR-CNS/RADAR-MongoDB-Sink-Connector/blob/struct/src/main/java/org/radarcns/sink/util/struct/StructAnalyser.java) could be used to provide possible new developers with all data formats used within the Platform. Starting form the `Avro Schema`, we can create the `Struct` counter part, the result `Bson Document` and the `CSV` file format reducing the level of knowledge that a new developer needs to have to start coding for RADAR.

Before merging 
- [x] Add `CODEOWNERS`
- [x] Add `schema` alpha release
- [ ] Enable end to end test for Empatica. This required a new release of `RADAR-Backend` linked to pull request https://github.com/RADAR-CNS/RADAR-Backend/pull/26

### CODE REVIEW

**Review by blootsvoets — APPROVED** [review]
This looks like a tremendous amount of work, good job! For another connector I just started working on, I discovered the `io.confluent.connect.avro.AvroData` class, dependency
```
   provided group: 'io.confluent', name: 'kafka-connect-avro-converter', version: confluentVersion
```
this also provides from and to schemas/struct/records. I discovered it a bit too late I see.

**Comment by fnobilia** [comment]
@blootsvoets is your code about `io.confluent.connect.avro.AvroData` public available?

**Comment by blootsvoets** [comment]
I don't, but it has just a few public functions to use
```java
int numSchemasToCache = 50;
AvroData avroData = new AvroData(numSchemasToCache);
Schema connectSchema = avroData.toConnectSchema(avroSchema);
Object connectRecord = avroData.toConnectData(record.getSchema(), record);
```
Keep the avroData object around so it can use its caching mechanism.

**Comment by fnobilia** [comment]
[AvroData](https://github.com/confluentinc/schema-registry/blob/master/avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java) is cool! We can definitely replace my converter with this.

**Comment by nivemaham** [comment]
AvroData looks very interesting.

**Review by nivemaham — APPROVED** [review]
Seems like a huge amount of work. Great job.

**Comment by afolarin** [comment]
@blootsvoets @nivemaham status of this one? Reviews were a bit on the old side now

**Comment by nivemaham** [comment]
@afolarin Indeed. It is old. This work mainly has some test code refactoring and updates. Not sure why we didn't merge it. If the test passes, i would say we could merge it and test the latest image.

**Pull request closed without merging**
